### ISSUE TITLE
pip install Politeness doesnt work

### ISSUE THREAD

**Issue by ArjunSarihyan** [sudhof/politeness#11]
**Tried using requirement.txt too, still doesnt work**
**The ERROR CODE is **

C:\Users\Arjun Sarihyan\Desktop\Project 2020>pip install -r requirements.txt
Collecting scipy==0.12.0
  Using cached scipy-0.12.0.tar.gz (9.1 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ARJUNS~1\\AppData\\Local\\Temp\\pip-install-q0239xg4\\scipy\\setup.py'"'"'; __file__='"'"'C:\\Users\\ARJUNS~1\\AppData\\Local\\Temp\\pip-install-q0239xg4\\scipy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ARJUNS~1\AppData\Local\Temp\pip-install-q0239xg4\scipy\pip-egg-info'
         cwd: C:\Users\ARJUNS~1\AppData\Local\Temp\pip-install-q0239xg4\scipy\
    Complete output (122 lines):
    blas_opt_info:
    blas_mkl_info:
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
      libraries mkl_rt not found in ['c:\\program files\\python37\\lib', 'C:\\', 'c:\\program files\\python37\\libs']
      NOT AVAILABLE

    blis_info:
      libraries blis not found in ['c:\\program files\\python37\\lib', 'C:\\', 'c:\\program files\\python37\\libs']
      NOT AVAILABLE

    openblas_info:
      libraries openblas not found in ['c:\\program files\\python37\\lib', 'C:\\', 'c:\\program files\\python37\\libs']
    get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
    customize GnuFCompiler
    Could not locate executable g77
    Could not locate executable f77
    customize IntelVisualFCompiler
    Could not locate executable ifort
    Could not locate executable ifl
    customize AbsoftFCompiler
    Could not locate executable f90
    customize CompaqVisualFCompiler
    Could not locate executable DF
    customize IntelItaniumVisualFCompiler
    Could not locate executable efl
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize G95FCompiler
    Could not locate executable g95
    customize IntelEM64VisualFCompiler
    customize IntelEM64TFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize PGroupFlangCompiler
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
      NOT AVAILABLE

    atlas_3_10_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas not found in ['c:\\program files\\python37\\lib', 'C:\\', 'c:\\program files\\python37\\libs']
      NOT AVAILABLE

    atlas_3_10_blas_info:
      libraries satlas not found in ['c:\\program files\\python37\\lib', 'C:\\', 'c:\\program files\\python37\\libs']
      NOT AVAILABLE

    atlas_blas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in ['c:\\program files\\python37\\lib', 'C:\\', 'c:\\program files\\python37\\libs']
      NOT AVAILABLE

    atlas_blas_info:
      libraries f77blas,cblas,atlas not found in ['c:\\program files\\python37\\lib', 'C:\\', 'c:\\program files\\python37\\libs']
      NOT AVAILABLE

    accelerate_info:
      NOT AVAILABLE

    blas_info:
      libraries blas not found in ['c:\\program files\\python37\\lib', 'C:\\', 'c:\\program files\\python37\\libs']
      NOT AVAILABLE

    blas_src_info:
      NOT AVAILABLE

    Running from scipy source directory.
    c:\program files\python37\lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
        Optimized (vendor) Blas libraries are not found.
        Falls back to netlib Blas library which has worse performance.
        A better performance should be easily gained by switching
        Blas library.
      if self._calc_info(blas):
    c:\program files\python37\lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      if self._calc_info(blas):
    c:\program files\python37\lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      if self._calc_info(blas):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ARJUNS~1\AppData\Local\Temp\pip-install-q0239xg4\scipy\setup.py", line 165, in <module>
        setup_package()
      File "C:\Users\ARJUNS~1\AppData\Local\Temp\pip-install-q0239xg4\scipy\setup.py", line 161, in setup_package
        configuration=configuration)
      File "c:\program files\python37\lib\site-packages\numpy\distutils\core.py", line 137, in setup
        config = configuration()
      File "C:\Users\ARJUNS~1\AppData\Local\Temp\pip-install-q0239xg4\scipy\setup.py", line 136, in configuration
        config.add_subpackage('scipy')
      File "c:\program files\python37\lib\site-packages\numpy\distutils\misc_util.py", line 1035, in add_subpackage
        caller_level = 2)
      File "c:\program files\python37\lib\site-packages\numpy\distutils\misc_util.py", line 1004, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\program files\python37\lib\site-packages\numpy\distutils\misc_util.py", line 941, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 9, in configuration
        config.add_subpackage('integrate')
      File "c:\program files\python37\lib\site-packages\numpy\distutils\misc_util.py", line 1035, in add_subpackage
        caller_level = 2)
      File "c:\program files\python37\lib\site-packages\numpy\distutils\misc_util.py", line 1004, in get_subpackage
        caller_level = caller_level + 1)
      File "c:\program files\python37\lib\site-packages\numpy\distutils\misc_util.py", line 941, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\integrate\setup.py", line 11, in configuration
        blas_opt = get_info('blas_opt',notfound_action=2)
      File "c:\program files\python37\lib\site-packages\numpy\distutils\system_info.py", line 471, in get_info
        return cl().get_info(notfound_action)
      File "c:\program files\python37\lib\site-packages\numpy\distutils\system_info.py", line 734, in get_info
        raise self.notfounderror(self.notfounderror.__doc__)
    numpy.distutils.system_info.BlasNotFoundError:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**And this is after creating a virtual environment**

**Comment by ArjunSarihyan** [comment]
And in addition to that all the things that are said to be not available cant be installed individually either.
All the issue requirements.txt file doesnt help either irrespective of being in or out of the virtual environment  created

**Comment by cristiandnm** [comment]
As noted in the Readme, this version is not supported anymore.  Please use the version in ConvoKit (convokit.cornell.edu) instead.  Thanks.
