### ISSUE TITLE
Spacy parser URL or other alternative?

### ISSUE THREAD

**Issue by bothe** [sudhof/politeness#12]
I am trying this repo recently, and I don't know if I am missing something at this line, missing URL for parsing the sentences? or another pointer would be helpful to reproduce the same results.

https://github.com/sudhof/politeness/blob/0449a15089479ee94ecad6b1698e8f3a2e5637ce/scripts/format_input.py#L14

Thanks in advance for the help.

**Comment by cristiandnm** [comment]
Thanks for your interest.  This is no longer maintained, so please use
convokit.cornell.edu instead

**Comment by bothe** [comment]
Thank you Cristian for your reply. I tried convokit, but wasn't that straight, I only wanted to check some sentences for Politeness labels with pre-trained model on wiki. 

I will give another try though.
